/**
 * Outreach Email Sender (tailor-side)
 *
 * Per-job outreach emails generated by the Tailor flow. SMTP creds +
 * From-name come from mongo `resumes.<username>.emailConfig` (set via
 * /settings). Resume PDF comes from mongo `resumes.<username>.pdf` (set
 * via the Resume page), unless an emailData.resumePath points at a
 * just-generated tailored PDF on disk — in which case that takes priority.
 */

import fs from "fs";
import path from "path";
import nodemailer from "nodemailer";
import dotenv from "dotenv";
import { markEmailAsSent, getUnsentEmails } from "./contact-logger.js";
import { getUserPdf, getEmailConfig } from "../resume-store.js";

dotenv.config();

// ============================================================
// CONFIG (mongo only)
// ============================================================

async function resolveSmtpConfig(username) {
  if (!username) {
    throw new Error('Username required — SMTP creds are per-user in Settings.');
  }
  const cfg = await getEmailConfig(username);
  if (!cfg?.smtp?.host || !cfg.smtp?.user || !cfg.smtp?.pass) {
    throw new Error(`No SMTP config in mongo for "${username}". Open /settings and fill in Email sending (SMTP) first.`);
  }
  return cfg;
}

function buildTransporter(cfg) {
  return nodemailer.createTransport({
    host: cfg.smtp.host,
    port: cfg.smtp.port,
    secure: cfg.smtp.secure,
    auth: { user: cfg.smtp.user, pass: cfg.smtp.pass },
  });
}

// Master PDF cache, keyed per username.
const _userPdfCache = new Map();
async function getUserPdfCached(username) {
  if (!username) return null;
  if (_userPdfCache.has(username)) return _userPdfCache.get(username);
  const promise = (async () => {
    try {
      const pdf = await getUserPdf(username);
      if (pdf?.buffer) return { filename: pdf.filename, buffer: pdf.buffer };
    } catch (err) {
      console.warn(`⚠️  mongo PDF fetch failed (${err.message})`);
    }
    return null;
  })();
  _userPdfCache.set(username, promise);
  return promise;
}

export function invalidateUserPdfCache(username) {
  if (username) _userPdfCache.delete(username);
  else _userPdfCache.clear();
}

// ============================================================
// VERIFY
// ============================================================

export async function verifyConnection(opts = {}) {
  try {
    const cfg = await resolveSmtpConfig(opts.username);
    await buildTransporter(cfg).verify();
    console.log(`✅ SMTP connection verified for ${opts.username}`);
    return true;
  } catch (error) {
    console.error("❌ SMTP connection failed:", error.message);
    return false;
  }
}

// ============================================================
// SEND
// ============================================================

/**
 * @param {Object} emailData - { to, subject, body, resumePath? }
 * @param {boolean|Object} opts - markSent flag (legacy) OR an options
 *                                 object { username, markSent }.
 */
export async function sendEmail(emailData, opts = true) {
  // Legacy callers passed a boolean as the second arg. New callers pass
  // { username, markSent }. Normalise both shapes.
  const o = typeof opts === 'object' && opts !== null
    ? opts
    : { username: null, markSent: opts !== false };
  const username = o.username;
  const markSent = o.markSent !== false;

  const { to, subject, body } = emailData;
  if (!username) {
    return { success: false, error: 'username required', to: to || null };
  }
  if (!to || !subject || !body) {
    throw new Error("Email must have to, subject, and body");
  }
  const actualRecipient = to;

  let cfg;
  try {
    cfg = await resolveSmtpConfig(username);
  } catch (err) {
    console.error(`❌ ${actualRecipient}: ${err.message}`);
    return { success: false, error: err.message, to: actualRecipient };
  }

  // Attachments: tailored PDF on disk first, then mongo master PDF.
  const attachments = [];
  const fromName = cfg.fromName || username;
  const cleanName = `${fromName.replace(/\s+/g, "_")}_Resume.pdf`;
  if (emailData.resumePath && fs.existsSync(emailData.resumePath)) {
    attachments.push({ filename: cleanName, path: emailData.resumePath });
    console.log(`   📎 Attaching tailored resume: ${path.basename(emailData.resumePath)} → ${cleanName}`);
  } else {
    const master = await getUserPdfCached(username);
    if (master?.buffer) {
      attachments.push({ filename: cleanName, content: master.buffer, contentType: 'application/pdf' });
    } else {
      console.warn(`⚠️  No resume PDF in mongo for "${username}" — email sent without attachment`);
    }
  }

  try {
    const info = await buildTransporter(cfg).sendMail({
      from: `"${fromName}" <${cfg.smtp.user}>`,
      to: actualRecipient,
      subject,
      text: body,
      attachments,
    });

    console.log(`✅ Email sent to ${actualRecipient} | messageId=${info.messageId}`);
    if (markSent) markEmailAsSent(to);
    return { success: true, messageId: info.messageId, to: actualRecipient };
  } catch (error) {
    console.error(`❌ Failed to send email to ${actualRecipient}:`, error.message);
    return { success: false, error: error.message, to: actualRecipient };
  }
}

/**
 * Send a batch of emails from a JSON file.
 *   sendEmailsFromFile(filePath, { username, delayMs })
 * Legacy single-arg form is no longer supported (username is required).
 */
export async function sendEmailsFromFile(filePath, opts = {}) {
  if (!opts.username) throw new Error('sendEmailsFromFile: opts.username required');
  if (!fs.existsSync(filePath)) throw new Error(`File not found: ${filePath}`);

  const emails = JSON.parse(fs.readFileSync(filePath, "utf-8"));
  if (!Array.isArray(emails) || emails.length === 0) {
    throw new Error("emails.json must contain an array of email objects");
  }
  console.log(`📧 Loaded ${emails.length} emails from ${filePath}`);

  const connected = await verifyConnection({ username: opts.username });
  if (!connected) throw new Error("SMTP connection failed — check /settings");

  const delayMs = opts.delayMs ?? 1200;
  const results = { sent: 0, failed: 0, errors: [] };
  for (let i = 0; i < emails.length; i++) {
    const email = emails[i];
    if (!email?.to || !email?.subject || !email?.body) {
      console.warn(`⚠️  Skipping index ${i}: missing to/subject/body`);
      results.failed++;
      continue;
    }
    const result = await sendEmail(email, { username: opts.username, markSent: false });
    if (result.success) results.sent++;
    else { results.failed++; results.errors.push({ to: email.to, error: result.error }); }
    if (i < emails.length - 1) await sleep(delayMs);
  }

  console.log("\n📊 SEND SUMMARY:");
  console.log(`   ✅ Sent: ${results.sent}`);
  console.log(`   ❌ Failed: ${results.failed}`);
  return results;
}

/**
 * Send every unsent email recorded in contacts.json.
 *   sendUnsentEmails(emailGenerator, { username, delayMs })
 */
export async function sendUnsentEmails(emailGenerator, opts = {}) {
  if (!opts.username) throw new Error('sendUnsentEmails: opts.username required');
  const unsentEmails = getUnsentEmails();
  if (unsentEmails.length === 0) {
    console.log("✅ No unsent emails found in contacts.json");
    return { sent: 0, failed: 0, errors: [] };
  }
  console.log(`📧 Found ${unsentEmails.length} unsent emails`);

  const connected = await verifyConnection({ username: opts.username });
  if (!connected) throw new Error("SMTP connection failed — check /settings");

  const delayMs = opts.delayMs ?? 1200;
  const results = { sent: 0, failed: 0, errors: [] };
  for (let i = 0; i < unsentEmails.length; i++) {
    const contact = unsentEmails[i];
    const emailData = await emailGenerator(contact);
    if (!emailData) {
      console.warn(`⚠️  Skipping ${contact.to}: email generator returned null`);
      results.failed++;
      continue;
    }
    const result = await sendEmail(emailData, { username: opts.username, markSent: true });
    if (result.success) results.sent++;
    else { results.failed++; results.errors.push({ to: contact.to, error: result.error }); }
    if (i < unsentEmails.length - 1) await sleep(delayMs);
  }
  console.log("\n📊 SEND SUMMARY:");
  console.log(`   ✅ Sent: ${results.sent}`);
  console.log(`   ❌ Failed: ${results.failed}`);
  return results;
}

function sleep(ms) { return new Promise((resolve) => setTimeout(resolve, ms)); }

export default {
  sendEmail,
  sendEmailsFromFile,
  sendUnsentEmails,
  verifyConnection,
  invalidateUserPdfCache,
};
